# jekyll serve --baseurl "" --watch
name: Web Application Guidelines 3.0
markdown: kramdown
pygments: true
exclude: [Gemfile, Gemfile.lock, .gitignore, README.md, COPYING, build.sh]
baseurl: /wag
cdn_url: //assets.malmo.se/internal/3.0
# cdn_url: //assets.malmo.se/internal/3.0-staging
# cdn_url: //www.local.malmo.se:3001/assets
permalink: /:categories/:title
relative_permalinks: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
